
# vim:set sw=2:
version: '3'
services:
  fuseki:
    image: stain/jena-fuseki
    ports:
      - "8000:3030"
    volumes:
      - fuseki-data:/fuseki
    environment:
      ADMIN_PASSWORD: secret
volumes:
  fuseki-data:
 

