#!/bin/bash

./scripts/sparql-query << EOQ
SELECT ?s ?name ?power
WHERE { ?s pd:baseDefense 120;
	   pd:baseAttack ?power;
	   pd:name ?name.
	FILTER ( lang(?name) = "en" ).
}
ORDER BY ?power
LIMIT 25
EOQ
