#!/bin/bash

OP=query
test "X$1" = "X--update" && OP=update && shift

(echo 'PREFIX pd: <http://pokedex.dataincubator.org/pkm/>'; cat ) \
| curl -i -s "http://localhost:8000/pokedex/$OP" \
	--data-urlencode "$OP@-" -H 'Accept: text/plain'
